Rails:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/SymbolArray:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - config/routes.rb

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bin/*'
    - 'config/**/*'

